Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,11 +1,22 @@
 #!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir> <env-dir>
 
+set -o errexit    # always exit on error
+set -o pipefail   # don't ignore exit codes when piping output
+set -o nounset    # fail on unset variables
+
+BUILD_DIR=${1:-}
+CACHE_DIR=${2:-}
 ENV_DIR=${3:-}
-build_dir=${1:-}
+BP_DIR=$(cd $(dirname ${0:-}); cd ..; pwd)
+
+source $BP_DIR/lib/environment.sh
+export_env_dir "$ENV_DIR"
+
 npm_token="${NPM_TOKEN:-$(cat $ENV_DIR/NPM_TOKEN)}"
 
 if [ "$npm_token" != "" ]; then
   echo "-----> Adding npm registry entry to .npmrc using environment variable NPM_TOKEN"
-  echo "//registry.npmjs.org/:_authToken=${npm_token}" >> "${build_dir}/.npmrc"
+  echo "//registry.npmjs.org/:_authToken=${npm_token}" >> "${BUILD_DIR}/.npmrc"
   exit 0
 fi
